server:
  servlet:
    encoding:
      enabled: true
      charset: UTF-8
    context-path: /galaxyinblue
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-8vo12e46.sql.tencentcdb.com:21475/galaxyinblue?serverTimezone=UTC&characterEncoding=utf8
    username: root
    password: 12243003MyMysql
    driver-class-name: com.mysql.cj.jdbc.Driver

  session:
    store-type: none